android emulator in vagrant - run the android emulator in vagrant and launch the app - ui testing with appium works on the host, but is unstable in vagrant   so only use the 'Activity Manger' to launch the app for now - to run it, the libvirt provider must be installed

diff --git a/deploy/vagrant-test-install/ubuntu2004-mobile/Vagrantfile b/deploy/vagrant-test-install/ubuntu2004-mobile/Vagrantfile
--- a/deploy/vagrant-test-install/ubuntu2004-mobile/Vagrantfile
+++ b/deploy/vagrant-test-install/ubuntu2004-mobile/Vagrantfile
@@ -7,23 +7,25 @@
 # you're doing.
 Vagrant.configure("2") do |config|
 
-  config.vm.box = "ubuntu/focal64"
+  config.vm.box = "generic/ubuntu2004"
 
   config.ssh.forward_agent = true
 
   config.ssh.insert_key = false
 
 
-  config.vm.provider "virtualbox" do |vb|  
+  config.vm.provider "libvirt" do |vb|  
     # Customize the amount of memory on the VM:
-    vb.memory = "4096"
+    vb.memory = "8192"
   end
-
 
   config.vm.provision "shell", inline: <<-SHELL
     set -e
     sudo apt update -q
     sudo apt upgrade -qqy
+
+    sudo apt-get -y install libpulse0 pulseaudio libxcursor-dev libxdamage-dev
+    sudo apt-get -y install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
 
     wget -qO - https://deb.nodesource.com/setup_16.x | bash -
     apt-get install -qqy nodejs
@@ -40,6 +42,14 @@ Vagrant.configure("2") do |config|
     sudo -u saltcorn /home/saltcorn/android_sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-11"
     sudo -u saltcorn /home/saltcorn/android_sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"
 
+    sudo adduser saltcorn kvm
+    yes | sudo -u saltcorn /home/saltcorn/android_sdk/cmdline-tools/latest/bin/sdkmanager "system-images;android-32;google_apis;x86_64"
+    echo "no" | sudo -u saltcorn /home/saltcorn/android_sdk/cmdline-tools/latest/bin/avdmanager create avd --force -n test -k "system-images;android-32;google_apis;x86_64" --device "pixel_xl"
+    
+    # start emulator
+    sudo -u saltcorn /home/saltcorn/android_sdk/emulator/emulator -avd test -memory 3072 -partition-size 8192 -no-audio -no-window -no-boot-anim -accel on -gpu swiftshader_indirect -no-snapshot-load &
+    sudo -u saltcorn /home/saltcorn/android_sdk/platform-tools/adb wait-for-device
+
     npm install -g npm@9.2.0
 
     sudo -u saltcorn wget -q https://services.gradle.org/distributions/gradle-7.1.1-all.zip
@@ -52,7 +62,36 @@ Vagrant.configure("2") do |config|
     export PATH=$PATH:/opt/gradle-7.1.1/bin
     export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=file\:/home/saltcorn/gradle-7.1.1-all.zip
 
+    sudo -u saltcorn /home/saltcorn/.local/bin/saltcorn create-user -e user@foo.com -r admin -p foobarbarfoo
     sudo -u saltcorn /home/saltcorn/.local/bin/saltcorn install-pack -n "Address book"
-    sudo --preserve-env=JAVA_HOME,ANDROID_SDK_ROOT,GRADLE_HOME,PATH,CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL -u saltcorn /home/saltcorn/.local/bin/saltcorn build-app -p "android" -s "http://10.0.2.2" -b "/home/saltcorn/build_dir" -e "EditPerson"
-  SHELL
-end
+    
+    echo "build apk"
+    sudo --preserve-env=JAVA_HOME,ANDROID_SDK_ROOT,GRADLE_HOME,PATH,CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL -u saltcorn /home/saltcorn/.local/bin/saltcorn build-app -c /home/saltcorn -u "user@foo.com" -p "android" -s "http://10.0.2.2" -b "/home/saltcorn/build_dir" -e "EditPerson"
+    sudo -u saltcorn /home/saltcorn/.local/bin/saltcorn serve &
+    set +e
+
+    echo "install apk"
+    sudo -u saltcorn /home/saltcorn/android_sdk/platform-tools/adb -s emulator-5554 install /home/saltcorn/app-debug.apk
+    
+    echo "start app"
+    START_TRY=0
+    sudo -u saltcorn /home/saltcorn/android_sdk/platform-tools/adb shell am start -n saltcorn.mobile.app/.MainActivity
+    LINES=$(sudo -u saltcorn /home/saltcorn/android_sdk/platform-tools/adb shell ps | grep saltcorn.mobile.app | wc -l)
+    while [ $LINES -eq 0 ] && [ $START_TRY -lt 50 ]; do
+      let START_TRY++
+      sleep 5
+      echo "re-try start app"
+      sudo -u saltcorn /home/saltcorn/android_sdk/platform-tools/adb shell am start -n saltcorn.mobile.app/.MainActivity
+      LINES=$(sudo -u saltcorn /home/saltcorn/android_sdk/platform-tools/adb shell ps | grep saltcorn.mobile.app | wc -l)
+    done
+
+    if [ $LINES -eq 1 ]; then
+      echo "success"
+      exit 0
+    else
+      echo "error: Unable to start the app"
+      exit 1
+    fi
+
+    SHELL
+  end
